import Head from "next/head";
import Cards from "../components/UI/Cards";
import Content from "../components/UI/Content";
import Footer from "../components/layout/Footer";
import Hero from "../components/UI/Hero";
import Navbar from "../components/layout/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Cards />
      <Content />
      <Footer />
    </>
  );
}
