import React from "react";

const ourService = () => {
  return <div>ourService</div>;
};

export default ourService;



// return (
//   <section>
//     <div className="py-20 h-full w-[80%] sm:w-[95%] mx-auto">
//       <div className="sm:w-[85%] mx-auto shadow-md bg-slate-300 dark:bg-black shadow-black dark:shadow-white  h-[50vh] md:h-[35vh] flex justify-center items-center text-center rounded-[1.5rem] sm:rounded-[3rem]">
//         <h1 className="font-bold animate-in fade-in zoom-in delay-120 duration-1000 text-center sm:text-4xl capitalize">
//           We build World Class Tech Talent!
//         </h1>
//       </div>

//       <div className="py-10 space-y-6">
//         <div>
//           <h1 className="max-w-3xl text-center mx-auto sm:text-xl font-medium">
//             Check out our available programs - add the register link here,
//             this should take them to the tech skill part where they check out
//             the course.
//           </h1>
//         </div>

//         {/*  */}
//         <div className="space-y-6">
//           <div className="">
//             <h1 className="font-bold sm:text-3xl text-xl text-center">
//               Get access to:
//             </h1>
//           </div>

//           <div className=" text-base grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-x-4 gap-y-5">
//             <h3 className="rounded-3xl animate-in fade-in zoom-in delay-120  hover:scale-105 ease-in  duration-100 shadow-md dark:shadow-white shadow-black mx-auto flex justify-center items-center h-60 w-full bg-slate-200 dark:bg-black">
//               Practical Exercises and Projects
//             </h3>
//             <h3 className="rounded-3xl animate-in fade-in zoom-in delay-120  hover:scale-105 ease-in  duration-300 shadow-md dark:shadow-white shadow-black mx-auto flex justify-center items-center h-60 w-full bg-slate-200 dark:bg-black">
//               Collaboration and Teamwork
//             </h3>
//             <h3 className="rounded-3xl animate-in fade-in zoom-in delay-120  hover:scale-105 ease-in  duration-500 shadow-md dark:shadow-white shadow-black mx-auto flex justify-center items-center h-60 w-full bg-slate-200 dark:bg-black">
//               Lifetime Access to Mentors
//             </h3>
//             <h3 className="rounded-3xl animate-in fade-in zoom-in delay-120  hover:scale-105 ease-in  duration-700 shadow-md dark:shadow-white shadow-black mx-auto flex justify-center items-center h-60 w-full bg-slate-200 dark:bg-black">
//               Continued Learning Resources
//             </h3>
//             <h3 className="rounded-3xl animate-in fade-in zoom-in delay-120  hover:scale-105 ease-in  duration-1000 shadow-md dark:shadow-white shadow-black mx-auto flex justify-center items-center h-60 w-full bg-slate-200 dark:bg-black">
//               Widely Accredited Certification
//             </h3>
//           </div>
//         </div>
//       </div>
//     </div>
//   </section>
// );